include:
  - docker-compose.yml

services:
  php:
    networks:
      - moodle
      - dokploy-network

  cron:
    networks:
      - moodle
      - dokploy-network

networks:
  dokploy-network:
    external: true
